### ISSUE TITLE
Add a section with our rule repository

### ISSUE THREAD

**Issue by utarwyn** [green-code-initiative/website#32]
Our rules are currently defined and presented as a Markdown table in the [ecoCode repository](https://github.com/green-code-initiative/ecoCode/blob/main/RULES.md). Although this centralizes the rules, they are still too hidden and poorly presented in an unclear table. What's more, we have to update it manually! So many possible inconsistencies.

To showcase all our painstaking work and make the rules available to as many people as possible, we need to present them in a different form. That's where a new section on the site comes in! 🔥 

### Important features are:

- List of all rules in the main repository (can be filtered/sorted by technologies, severity)
- Detail of all rules with descriptions, infos and references
- Automatically updated to avoid inconsistencies

### Let's get down to a bit of architecture!

This schema briefly presents the idea and how the repositories will communicate with each other (in french).

![image](https://github.com/user-attachments/assets/336922d4-6346-48e6-8614-2c3a55364919)

### This EPIC can be splitted into small tasks:

- [x] 1. Check the technical feasibility of integration with the tool 
- [x] 2. Web and mobile design
- [ ] 3. Create the automated task to build rule metadatas 
- [x] 4. Website integration
