### ISSUE TITLE
Turn the site into a showcase for the collective

### ISSUE THREAD

**Issue by utarwyn** [green-code-initiative/website#33]
The main idea behind the site was to present the ecoCode project.
But we'd like to turn it into a public site for the Green Code Initiative collective, showcasing all our projects and news. This will require a complete reorganization of sections and content. The ecoCode project will continue to feature prominently, with a dedicated section.

### This EPIC can be splitted into small tasks:

- [ ] 1. Prepare content and editorial line
- [ ] 2. Think about the new website structure
- [ ] 3. Rework the home page
- [ ] *to be defined...*
